export const plans = [
  {
    id: "free",
    name: "Free",
    price: "$0",
    period: "forever",
    badge: null,
    desc: "Everything you need to build and export a great resume.",
    cta: "Get Started Free",
    ctaHref: "/register",
    ctaStyle: "outline" as const,
    features: [
      "1 resume",
      "3 templates (Modern, Classic, Minimal)",
      "Live preview & PDF export",
      "All 4 builder steps",
      "3 AI uses per month",
    ],
    unavailable: [
      "Premium templates",
      "Unlimited AI tools",
      "DOCX export",
      "Priority support",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    price: "$9",
    period: "per month",
    badge: "Most Popular",
    desc: "Unlimited AI power for serious job seekers.",
    cta: "Start 7-Day Free Trial",
    ctaHref: "/register?plan=pro",
    ctaStyle: "filled" as const,
    features: [
      "Unlimited resumes",
      "All 10 templates + premium ones",
      "PDF & DOCX export",
      "Unlimited AI generations",
      "ATS Simulator",
      "JD Match & 1-click optimize",
      "Cover Letter Generator",
      "Grammar & Clarity Check",
      "Achievement Generator",
      "Career Gap Explainer",
      "Interview Prep",
      "Priority support",
    ],
    unavailable: [],
  },
];
